#!/bin/bash

# Exit on first error
set -ex

# Kill background processes on exit
trap 'kill -9 $(jobs -p)' SIGINT SIGTERM EXIT

# Start docker daemon
sekexe/run "docker -d -H 0.0.0.0:4243 2>> /dev/null >> /dev/null" &
sleep 2

export DOCKER_HOST="tcp://10.1.1.1:4243"
nosetests -v
